---
title: "datawrangling_titanic"
author: "Mandar Mulherkar"
date: "Apr 2, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

This is the second exercise to clean the titanic dataset for missing values.

```{r , echo=FALSE}
library(ggplot2)
```

## Setting up the data frame. Using the file from springboard

```{r}
# titanic is avaliable in your workspace

# Check out the structure of titanic
str(titanic)

# Use ggplot() for the first instruction
ggplot(titanic, aes(factor(Pclass)), fill = factor(Sex), position = "dodgy") + geom_bar()

# Use ggplot() for the second instruction
ggplot(  titanic, aes(factor(Pclass)), fill = factor(Sex), position = "dodgy") + geom_bar() + facet_grid(.~Survived)

# Position jitter (use below)
posn.j <- position_jitter(0.5, 0)

# Use ggplot() for the last instruction
ggplot(titanic, aes(factor(Pclass), Age ,col = factor(Sex)), position = "dodgy") + geom_jitter(size = 3, alpha = 0.5, position = posn.j) + facet_grid(.~Survived)
```